### ISSUE TITLE
Fail to compile 

### ISSUE THREAD

**Issue by pjaraherrera** [erikschlegel/React-Twitter-Typeahead#2]
Hi
I am trying this library in my project and occurs a error when compiling with browserify. I installed it with npm and in my .js file I used Var ReactTypeahead = require('react-twitter-typeahead');

compiled it with: browserify -t reactify archivo.js -o archivo_preprocesado.js

```
Error: Parsing file /home/patricio/programacion/trabajos/capex/moiras/browser/javascript/node_modules/react-twitter-typeahead/lib/js/react-typeahead.js: Unexpected token (78:12)
    at Deps.parseDeps (/usr/local/lib/node_modules/browserify/node_modules/module-deps/index.js:436:28)
    at fromSource (/usr/local/lib/node_modules/browserify/node_modules/module-deps/index.js:375:44)
    at /usr/local/lib/node_modules/browserify/node_modules/module-deps/index.js:369:17
    at ConcatStream.<anonymous> (/usr/local/lib/node_modules/browserify/node_modules/concat-stream/index.js:36:43)
    at ConcatStream.emit (events.js:117:20)
    at finishMaybe (/usr/local/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:460:14)
    at endWritable (/usr/local/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:469:3)
    at ConcatStream.Writable.end (/usr/local/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:436:5)
    at DuplexWrapper.onend (/usr/local/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:537:10)
    at DuplexWrapper.g (events.js:180:16)
```

**Comment by erikschlegel** [comment]
Hi @nornak, Im taking a look at the issue now.

Erik

**Comment by erikschlegel** [comment]
I pushed out a fix and re-published to NPM which should resolve the issue. I'll leave this open til end of day, just in case you run into any other problems.

Thanks for pointing this out and apologies for any frustrations this caused.

Erik

**Comment by pjaraherrera** [comment]
Thanks, now compiled an ran without problems :D

**Comment by erikschlegel** [comment]
Great to hear. Let me know if there's anything else you need. 

Erik

**Comment by erikschlegel** [comment]
@nornak confirmed the issue is fixed 

Erik
